/**
 * PDF Generator Utility — Member 4: PDF Export Engine
 *
 * Generates a professional multi-page PDF Startup Kit using jsPDF & jspdf-autotable.
 * Includes:
 * 1. Business Plan & Executive Summary
 * 2. Branding & Marketing Strategy
 * 3. Website Content & Copy
 * 4. Financial Modeling & Monthly Projections
 *    - KPI summary table
 *    - 6-month growth projections table
 *    - Cost distribution breakdown table
 *    - Financial Health Score section
 * 5. Government Compliance Checklist (Registrations, Fees, Docs, Timelines)
 * 6. Pitch Deck Summary
 *
 * Each page includes a header, footer, and CONFIDENTIAL watermark.
 */

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatCurrency } from './financeCalculator'

// ─── Color constants ───────────────────────────────────────────────────────────
const PRIMARY   = [49, 130, 206]   // #3182CE Blue
const DARK      = [30, 41, 59]     // #1E293B Dark Slate
const LIGHT_BG  = [248, 250, 252]  // #F8FAFC
const EMERALD   = [16, 185, 129]   // #10B981
const PURPLE    = [99, 102, 241]   // #6366F1

export function generateStartupKitPDF(kitData) {
  if (!kitData) {
    throw new Error('No startup kit data provided for PDF export.')
  }

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const branding    = kitData.branding     || {}
  const plan        = kitData.businessPlan || {}
  const website     = kitData.website      || {}
  const marketing   = kitData.marketing    || {}
  const fin         = kitData.finance      || {}
  const comp        = kitData.compliance   || {}
  const pitch       = kitData.pitchDeck    || {}

  let y

  // ── Helper: Page header ───────────────────────────────────────────────────
  function addHeader(title) {
    doc.setFillColor(...PRIMARY)
    doc.rect(0, 0, 210, 12, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('STARTUP FORGE — OFFICIAL STARTUP KIT REPORT', 14, 8)
    doc.setFont('helvetica', 'normal')
    doc.text(title, 196, 8, { align: 'right' })
    doc.setTextColor(...DARK)
  }

  // ── Helper: Page footer ───────────────────────────────────────────────────
  function addFooter(pageNum) {
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Generated by Startup Forge AI Platform | Confidential | Page ${pageNum}`,
      105, 287,
      { align: 'center' }
    )
    // Footer divider line
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.3)
    doc.line(14, 283, 196, 283)
  }

  // ── Helper: Diagonal CONFIDENTIAL watermark ───────────────────────────────
  function addWatermark() {
    doc.saveGraphicsState()
    doc.setGState(doc.GState({ opacity: 0.04 }))
    doc.setFontSize(48)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 41, 59)
    doc.text('CONFIDENTIAL', 105, 148, {
      align: 'center',
      angle: 45,
    })
    doc.restoreGraphicsState()
  }

  // ── Helper: Section heading ───────────────────────────────────────────────
  function sectionHeading(text, yPos) {
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...DARK)
    doc.text(text, 14, yPos)
    // Underline
    doc.setDrawColor(...PRIMARY)
    doc.setLineWidth(0.5)
    doc.line(14, yPos + 1, 60, yPos + 1)
    doc.setDrawColor(0, 0, 0)
  }

  // ── Helper: compute health score from fin data ────────────────────────────
  function computeHealthScore() {
    const rev  = fin.revenue       || 0
    const prof = fin.profit        || 0
    const roi  = fin.roiPercentage || 0
    const marginPct = rev > 0 ? (prof / rev) * 100 : 0
    return Math.round(
      (Math.min(100, Math.max(0, roi)) * 0.5) +
      (Math.min(100, Math.max(0, marginPct)) * 0.5)
    )
  }

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 1: COVER & EXECUTIVE SUMMARY
  // ─────────────────────────────────────────────────────────────────────────
  addHeader('Overview & Business Plan')
  addWatermark()

  // Cover banner
  doc.setFillColor(...LIGHT_BG)
  doc.roundedRect(14, 14, 182, 44, 3, 3, 'F')
  doc.setFillColor(...PRIMARY)
  doc.rect(14, 14, 5, 44, 'F')

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...PRIMARY)
  doc.text(branding.name || kitData._idea || 'Startup Launch Kit', 24, 27)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(71, 85, 105)
  doc.text(branding.tagline || 'AI-Generated Data-Driven Startup Plan', 24, 35)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  doc.text(
    `Industry: ${kitData._industry || kitData.industry || 'Technology'} | Budget: ${kitData._budget || kitData.budget || 'TBD'} | Type: ${kitData._businessType || 'General'}`,
    24, 43
  )
  doc.text(
    `Generated: ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    24, 50
  )

  y = 68

  // Executive Summary
  sectionHeading('1. Executive Summary', y)
  y += 7
  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(51, 65, 85)
  const execText = doc.splitTextToSize(plan.executiveSummary || 'No executive summary provided.', 182)
  doc.text(execText, 14, y)
  y += execText.length * 5 + 8

  // Problem & Solution
  sectionHeading('2. Problem & Solution', y)
  y += 7

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(225, 29, 72)
  doc.text('Problem Statement:', 14, y)
  y += 5
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(51, 65, 85)
  const probText = doc.splitTextToSize(plan.problem || 'N/A', 182)
  doc.text(probText, 14, y)
  y += probText.length * 5 + 4

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...EMERALD)
  doc.text('Proposed Solution:', 14, y)
  y += 5
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(51, 65, 85)
  const solText = doc.splitTextToSize(plan.solution || 'N/A', 182)
  doc.text(solText, 14, y)
  y += solText.length * 5 + 8

  // Market Analysis
  sectionHeading('3. Market Opportunity', y)
  y += 7
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(51, 65, 85)
  const mktText = doc.splitTextToSize(plan.marketAnalysis || 'N/A', 182)
  doc.text(mktText, 14, y)

  addFooter(1)

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 2: BRANDING, WEBSITE & MARKETING
  // ─────────────────────────────────────────────────────────────────────────
  doc.addPage()
  addHeader('Branding, Website & Marketing')
  addWatermark()
  y = 20

  sectionHeading('4. Branding & Visual Identity', y)
  y += 7

  autoTable(doc, {
    startY: y,
    head: [['Attribute', 'Details']],
    body: [
      ['Brand Name',       branding.name     || 'N/A'],
      ['Tagline',          branding.tagline   || 'N/A'],
      ['Mission Statement',branding.mission   || 'N/A'],
      ['Core Values',      Array.isArray(branding.values) ? branding.values.join(', ') : (branding.values || 'N/A')],
      ['Brand Colors',     `Primary: ${branding.colors?.primary || '#3b82f6'} | Secondary: ${branding.colors?.secondary || '#6366f1'} | Accent: ${branding.colors?.accent || '#f59e0b'}`],
    ],
    theme: 'striped',
    headStyles: { fillColor: PRIMARY, textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 8.5, cellPadding: 3 },
  })

  y = doc.lastAutoTable.finalY + 10

  sectionHeading('5. Website Copy & Landing Page', y)
  y += 7

  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text(`Hero Headline: "${website.heroHeadline || 'N/A'}"`, 14, y)
  y += 5
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(9)
  doc.text(`Subtitle: "${website.heroSubtitle || 'N/A'}"`, 14, y)
  y += 6

  if (Array.isArray(website.features) && website.features.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Key Feature', 'Description']],
      body: website.features.map((f) => [f.title, f.description]),
      theme: 'grid',
      headStyles: { fillColor: [71, 85, 105], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 2.5 },
    })
    y = doc.lastAutoTable.finalY + 10
  }

  sectionHeading('6. Marketing Strategy & Channels', y)
  y += 7

  if (Array.isArray(marketing.channels) && marketing.channels.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Channel', 'Growth Strategy']],
      body: marketing.channels.map((c) => [c.name, c.strategy]),
      theme: 'striped',
      headStyles: { fillColor: PRIMARY, textColor: 255 },
      styles: { fontSize: 8, cellPadding: 2.5 },
    })
  }

  addFooter(2)

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 3: FINANCIAL MODEL & PROJECTIONS
  // ─────────────────────────────────────────────────────────────────────────
  doc.addPage()
  addHeader('Financial Modeling & Analytics')
  addWatermark()
  y = 20

  sectionHeading('7. Financial Projections & Key Metrics (Module 1)', y)
  y += 8

  const calcInv       = fin.investment      || 500000
  const calcRev       = fin.revenue         || 200000
  const calcExp       = fin.totalExpenses   || fin.expenses || 120000
  const calcProf      = fin.profit          || (calcRev - calcExp)
  const calcBreakEven = fin.breakEvenMonths || fin.breakEven    || '7 Months'
  const calcRoi       = fin.roiPercentage   !== undefined ? `${fin.roiPercentage}%` : (fin.roi || '192%')
  const healthScore   = computeHealthScore()

  // ── Financial Health Score box ────────────────────────────────────────────
  const hsColor = healthScore >= 70 ? [...EMERALD] : healthScore >= 45 ? [245, 158, 11] : [239, 68, 68]
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(14, y, 182, 18, 2, 2, 'F')
  doc.setFillColor(...hsColor)
  doc.roundedRect(14, y, 5, 18, 2, 0, 'F')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Financial Health Score', 24, y + 7)

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...hsColor)
  doc.text(`${healthScore}/100`, 24, y + 14)

  const hsLabel = healthScore >= 70 ? 'Excellent' : healthScore >= 45 ? 'Moderate' : healthScore >= 20 ? 'Weak' : 'Critical'
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text(`Status: ${hsLabel} — profit margin & ROI composite score`, 65, y + 11)

  y += 24

  // ── KPI Summary Table ─────────────────────────────────────────────────────
  autoTable(doc, {
    startY: y,
    head: [['Initial Investment', 'Monthly Revenue', 'Monthly Expenses', 'Estimated Profit', 'Break-even', 'Annual ROI']],
    body: [[
      formatCurrency(calcInv),
      formatCurrency(calcRev),
      formatCurrency(calcExp),
      formatCurrency(calcProf),
      calcBreakEven,
      calcRoi,
    ]],
    theme: 'grid',
    headStyles: { fillColor: DARK, textColor: 255, halign: 'center', fontStyle: 'bold' },
    bodyStyles: { halign: 'center', fontStyle: 'bold', fontSize: 9 },
    styles: { cellPadding: 4 },
  })

  y = doc.lastAutoTable.finalY + 10

  // ── 6-Month Growth Projections Table ─────────────────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('6-Month Growth Projections Table', 14, y)
  y += 5

  const projRows = (fin.projections || [
    { month: 'Month 1', customers: 800,  revenue: calcRev,                    expenses: calcExp,                    profit: calcProf },
    { month: 'Month 2', customers: 864,  revenue: Math.round(calcRev * 1.08), expenses: Math.round(calcExp * 1.02), profit: Math.round(calcRev * 1.08 - calcExp * 1.02) },
    { month: 'Month 3', customers: 933,  revenue: Math.round(calcRev * 1.17), expenses: Math.round(calcExp * 1.04), profit: Math.round(calcRev * 1.17 - calcExp * 1.04) },
    { month: 'Month 4', customers: 1008, revenue: Math.round(calcRev * 1.26), expenses: Math.round(calcExp * 1.06), profit: Math.round(calcRev * 1.26 - calcExp * 1.06) },
    { month: 'Month 5', customers: 1089, revenue: Math.round(calcRev * 1.36), expenses: Math.round(calcExp * 1.08), profit: Math.round(calcRev * 1.36 - calcExp * 1.08) },
    { month: 'Month 6', customers: 1175, revenue: Math.round(calcRev * 1.47), expenses: Math.round(calcExp * 1.10), profit: Math.round(calcRev * 1.47 - calcExp * 1.10) },
  ]).map((p) => {
    const margin = p.revenue > 0 ? `${((p.profit / p.revenue) * 100).toFixed(1)}%` : '0%'
    return [
      p.month || p.name,
      p.customers ? p.customers.toLocaleString('en-IN') : '—',
      formatCurrency(p.revenue),
      formatCurrency(p.expenses),
      formatCurrency(p.profit),
      margin,
    ]
  })

  autoTable(doc, {
    startY: y,
    head: [['Month', 'Customers', 'Revenue', 'Expenses', 'Net Profit', 'Margin']],
    body: projRows,
    theme: 'striped',
    headStyles: { fillColor: PRIMARY, textColor: 255 },
    columnStyles: {
      2: { textColor: [37, 99, 235] },
      4: { fontStyle: 'bold' },
    },
    styles: { fontSize: 8.5, cellPadding: 3 },
  })

  y = doc.lastAutoTable.finalY + 10

  // ── Cost Distribution Table ───────────────────────────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Operating Cost Breakdown', 14, y)
  y += 5

  const costRows = (fin.costDistribution || [
    { name: 'Employee Salaries',       value: Math.round(calcExp * 0.35) },
    { name: 'Marketing & CAC',         value: Math.round(calcExp * 0.25) },
    { name: 'Operations & Logistics',  value: Math.round(calcExp * 0.22) },
    { name: 'Tech & Infrastructure',   value: Math.round(calcExp * 0.10) },
    { name: 'Legal & Administrative',  value: Math.round(calcExp * 0.08) },
  ]).map((c) => [
    c.name,
    formatCurrency(c.value),
    calcExp > 0 ? `${((c.value / calcExp) * 100).toFixed(1)}%` : '—',
  ])

  autoTable(doc, {
    startY: y,
    head: [['Cost Category', 'Monthly Amount', '% of Total Expenses']],
    body: costRows,
    theme: 'striped',
    headStyles: { fillColor: [...PURPLE], textColor: 255 },
    styles: { fontSize: 8.5, cellPadding: 3 },
  })

  y = doc.lastAutoTable.finalY + 10

  // ── 3-Year Long-Term Outlook ──────────────────────────────────────────────
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('3-Year Long-Term Revenue Outlook', 14, y)
  y += 5

  const yr1 = fin.yearlyProjection?.year1 || calcRev * 12
  const yr2 = fin.yearlyProjection?.year2 || calcRev * 12 * 1.6
  const yr3 = fin.yearlyProjection?.year3 || calcRev * 12 * 2.8

  autoTable(doc, {
    startY: y,
    head: [['Year 1 Revenue Goal', 'Year 2 Projected Revenue', 'Year 3 Scaled Target']],
    body: [[formatCurrency(yr1), formatCurrency(yr2), formatCurrency(yr3)]],
    theme: 'grid',
    headStyles: { fillColor: [...EMERALD], textColor: 255, halign: 'center' },
    bodyStyles: { halign: 'center', fontStyle: 'bold', fontSize: 9.5 },
  })

  addFooter(3)

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 4: COMPLIANCE ENGINE & LEGAL ROADMAP
  // ─────────────────────────────────────────────────────────────────────────
  doc.addPage()
  addHeader('Legal & Compliance Engine')
  addWatermark()
  y = 20

  sectionHeading('8. Government Registrations & Statutory Checklist (Module 2)', y)
  y += 8

  const checklistItems = (comp.checklist || comp.registrations || []).map((r) => {
    const name   = typeof r === 'string' ? r : r.title || r.item || 'Registration'
    const reason = r.reason || 'Statutory requirement for business operation.'
    const docs   = Array.isArray(r.requiredDocs) ? r.requiredDocs.join(', ') : (r.requiredDocs || 'PAN, Aadhaar, Premises Proof')
    const fee    = r.estimatedFee || r.fee || '₹0 - ₹1,500'
    const time   = r.processingTime || r.time || '7 - 14 Days'
    const status = r.status || 'Pending'
    return [name, reason, docs, fee, time, status]
  })

  if (checklistItems.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Registration', 'Why it is needed', 'Required Documents', 'Est. Fee', 'Timeline', 'Status']],
      body: checklistItems,
      theme: 'grid',
      headStyles: { fillColor: PRIMARY, textColor: 255, fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 32, fontStyle: 'bold' },
        1: { cellWidth: 42 },
        2: { cellWidth: 45 },
        3: { cellWidth: 22 },
        4: { cellWidth: 22 },
        5: { cellWidth: 18, fontStyle: 'bold' },
      },
      styles: { fontSize: 7.5, cellPadding: 2.5, overflow: 'linebreak' },
    })
    y = doc.lastAutoTable.finalY + 10
  }

  // Permits & Legal Docs summary
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Industry Permits & Recommended Legal Contracts', 14, y)
  y += 5

  const permits   = Array.isArray(comp.licenses)  ? comp.licenses.join('\n• ')  : 'Shop & Establishment, Local Municipal License'
  const legalDocs = Array.isArray(comp.legalDocs) ? comp.legalDocs.join(', ')   : 'Terms of Service, Privacy Policy, Founder Agreement'

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Details & Requirements']],
    body: [
      ['Permits & Licenses',     `• ${permits}`],
      ['Required Legal Contracts', legalDocs],
      ['Legal Advice Note',      comp.legalRecommendations || 'Ensure all statutory registrations are filed before starting commercial sales to avoid penalties.'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [71, 85, 105], textColor: 255 },
    styles: { fontSize: 8, cellPadding: 3 },
  })

  addFooter(4)

  // ─────────────────────────────────────────────────────────────────────────
  // PAGE 5: PITCH DECK SUMMARY
  // ─────────────────────────────────────────────────────────────────────────
  doc.addPage()
  addHeader('Pitch Deck Summary')
  addWatermark()
  y = 20

  sectionHeading('9. Pitch Deck Summary & Investment Ask', y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Slide Section', 'Content Overview']],
    body: [
      ['Problem',              pitch.problem      || plan.problem       || 'N/A'],
      ['Solution',             pitch.solution     || plan.solution      || 'N/A'],
      ['Market Opportunity',   pitch.market       || plan.marketAnalysis || 'N/A'],
      ['Business Model',       pitch.businessModel|| plan.revenueModel  || 'N/A'],
      ['Traction / Milestones',pitch.traction     || 'Pre-launch planning & MVP development phase.'],
      ['Investment Ask',       pitch.ask          || `Seeking ${formatCurrency(calcInv)} initial seed funding for 12 months runway.`],
    ],
    theme: 'grid',
    headStyles: { fillColor: PRIMARY, textColor: 255 },
    columnStyles: { 0: { cellWidth: 40, fontStyle: 'bold' } },
    styles: { fontSize: 8.5, cellPadding: 3.5 },
  })

  y = doc.lastAutoTable.finalY + 14

  // Final summary box
  doc.setFillColor(...LIGHT_BG)
  doc.roundedRect(14, y, 182, 28, 3, 3, 'F')
  doc.setFillColor(...EMERALD)
  doc.roundedRect(14, y, 5, 28, 2, 0, 'F')

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Generated by Startup Forge AI Platform', 24, y + 9)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text('This document is confidential and intended solely for the named founder(s).', 24, y + 16)
  doc.text('All projections are estimates based on user inputs and should not be treated as financial advice.', 24, y + 22)

  addFooter(5)

  // ── Save ──────────────────────────────────────────────────────────────────
  const fileName = `${(branding.name || 'Startup').toLowerCase().replace(/\s+/g, '_')}_startup_kit.pdf`
  doc.save(fileName)
}
